### ISSUE TITLE
Can’t scroll the extension’s pane

### ISSUE THREAD

**Issue by riddle** [MrJPGames/WayFarerPlus#102]
I had to resort to CSS tricks moving panels up with position:relative and negative top on panels to be able to see and click various settings. Google Chrome Store build, newest stable Chrome (Version 79.0.3945.130 (Official Build) (64-bit))

https://www.whatsmybrowser.org/b/ITX65

**Comment by MrJPGames** [comment]
Sadly I'm unable to reproduce this issue. I am running Chrome version 80, however that shouldn't make much of a difference here. I'll try downgrading when I've got more time to research the issue. Until then you could possibly help by providing the version of the extension (as shown in chrome://extensions). Any further info that could help me diagnose this problem would also be greatly appreciated!

Thanks for your report!

**Comment by riddle** [comment]
WayFarer+ 1.11.3

I’ve found that removing `box-sizing: border-box;` from <html> element allows scrollbars to appear and everything works the way you intended, with small exception of blue headers being a tad too wide and clipped by the right side of the panel.

I’ll be using this workaround for now, hoping you can reproduce it on your end.

**Comment by MrJPGames** [comment]
Sadly I am still unable to reproduce this issue. Removing box-sizing does still work on all browsers, but makes some content disappear behind the scroll bar, and as such is not desirable. If you find a solution that doesn't cause other issues I'd be glad to hear them, but as I can't reproduce the issue finding a good solution from my end will be rather difficult. 

You could also try updating to the latest version of Chrome and see if that fixes the issue.

**Comment by mariomc** [comment]
I had the same issue on my Mac when on the trackpad only. The way I solved it was to toggle ON the Show scrollbars as detailed below:
![Instructions](https://cdn.osxdaily.com/wp-content/uploads/2011/08/howto-always-show-scroll-bars-mac-os-x.jpg)

**Comment by riddle** [comment]
Appreciate the tip but there is no way I’m changing that for 1 plugin 😆 

--
Sent from my iPhone

> On 21 Mar 2020, at 11:24, Mário Gonçalves <notifications@github.com> wrote:
> 

﻿
I had the same issue on my Mac when on the trackpad only. The way I solved it was to toggle ON the Show scrollbars as detailed below:

**Comment by mariomc** [comment]
> Appreciate the tip but there is no way I’m changing that for 1 plugin 😆

You're right. I've managed to replicate the issue and the solution I've found is to make the container element slightly bigger than the viewport's (the popup) height. The proposed solution doesn't have the same issues as the `content-box` approach.

Can you try it in your end to see if it fixes the issue as well, @riddle ?

**Comment by MrJPGames** [comment]
The fix by mariomc has been accepted and will be live on Firefox in a few minutes. Chrome's review process means it will likely take 1-2 days for it to go live there.
