### ISSUE TITLE
Allow two levels of S2 cells to be displayed on the maps

### ISSUE THREAD

**Issue by duck57** [MrJPGames/WayFarerPlus#125]
**Describe the feature you'd like**
(see title)

**Describe reasons NOT to add this feature**
A minor performance hit, L14 cells may be too big for a zoomed-in map and add silly-looking lines until you zoom out.

**Describe reasons to add this feature**
Displaying both L14 and L17 cells would show whether the nomination in question would help with creating a new Pokémon gym.  It would also make deliberate GPS drift in the submission more obvious for the previously-stated reasons.

**Additional context**
Currently, we have one user-selectable cell level to view.  A preset for both gym and stop cells at the same time would be useful for the above reasons.

**Comment by MrJPGames** [comment]
Sorry to only get back to you now. I somehow missed the email notification... I have just added this and am now rolling it out to extension stores!
