### ISSUE TITLE
[BUG] Countdown timer starts at 29 seconds, no matter the setting

### ISSUE THREAD

**Issue by OGMagus** [MrJPGames/WayFarerPlus#149]
I expected the time to chance once I changed it in Review Settings, like it used to before

using Chrome 81.0.4044.122

**Comment by MrJPGames** [comment]
Have you checked your local time? It is likely at fault here, to know the difference in time the local time is used. This is to make sure a refresh doesn't restart the countdown timer.

The next version will deal better with incorrect local time though!

**Comment by MrJPGames** [comment]
I will assume it was an issue with your local time settings, as I've not been able to reproduce the issue. If this issue is still occurring for you feel free to reopen this issue!
