### ISSUE TITLE
Please move the Nomination Map to the bottom of the Nominations page (or at least add this as an option)

### ISSUE THREAD

**Issue by Andrefpvs** [MrJPGames/WayFarerPlus#155]
I like the Nomination Map, but it being on the top of the Nominations page means I always have to scroll down to see my nomination list, which is what I'm looking for more often.

Moving the map to the bottom would allow us to view it only when we desire. It would also keep the map consistent with the Review History map, which appears on the bottom of the Profile page.

If there are good reasons to keep it on top, then maybe perhaps add this as an option?

Thank you very much!

**Comment by MrJPGames** [comment]
The fix I ended up going with is no longer having the map open by default, so instead you can now open it when you want, this way it takes up significantly less space until opened.

If this is still not a good solution feel free to comment with more suggestions and I can reopen this issue.
