### ISSUE TITLE
[BUG] GoogleTranslate and the "&"

### ISSUE THREAD

**Issue by Un1matr1x** [MrJPGames/WayFarerPlus#156]
**Describe the bug**
If the title of a review contains the &-symbole, the translation will end at this point

**To Reproduce**
Do a review
wait till the &-symbole is in a name
click on translate-icon or translate all
only half is translatet

**Expected behavior**
the hole title should be translatet

**Additional context**
Stenen & Brønden
leads to
https://translate.google.com/?sl=auto&q=Stenen%20&%20Br%C3%B8nden

**Comment by MrJPGames** [comment]
Must've forgotten to URI encode the string... Thanks for reporting should be fixed soon, and the version with the fix live in a few hours max.
