### ISSUE TITLE
[BUG] review: Uncaught ReferenceError: applyMapOptions is not defined

### ISSUE THREAD

**Issue by AlterTobi** [MrJPGames/WayFarerPlus#157]
Wayfarer Version: 1.14.3.1

**Describe the bug**
error message in console log

mapMods.js:170 Uncaught ReferenceError: applyMapOptions is not defined
    at makeMap3D (mapMods.js:170)
    at HTMLDocument.setupMapMods (mapMods.js:57)
    at hookedAll (main.js:33)

**To Reproduce**
1. open console
2. open review page

**Browser (please complete the following information):**
latest Chrome (Version 81.0.4044.129 (Offizieller Build) (64-Bit))

**Comment by MrJPGames** [comment]
Thanks for the report a new version with a fix for this bug is now rolling out to chrome and firefox!
