### ISSUE TITLE
[BUG] Search by date of nominations' review history is cutting some results

### ISSUE THREAD

**Issue by Paranomix** [MrJPGames/WayFarerPlus#161]
**Describe the bug**
Searching by date is cutting off some results. Search from day X to day Y and cutted half of the reviews done in day Y. Didn't notice any other cuts, so I assume it has to do with timezoned search, cutting part of results, since it bases the search on not my timezone. I assume day X would also have cuts, it just didn't happen due to the times I reviewed that day's nominations.

**To Reproduce**
1. Go to 'Profile'
2. Scroll down to 'Nomination's History'
3. Click on 'Datepicker'
4. Select a date
5. Hope you have a different timezone than the default of datepicker
6. Hope you have "cuttable" reviews
7. Analize cuts

**Expected behavior**
That all reviews that have its date registered as Z, Z contained in [X,Y], be shown.

**Screenshots**
With search:
![image](https://user-images.githubusercontent.com/37214973/81499572-7dcc2e80-92c4-11ea-9efd-674cf75efd28.png)

Without search:
![image](https://user-images.githubusercontent.com/37214973/81499593-a18f7480-92c4-11ea-8e54-0fadd60fd32b.png)

**Browser (please complete the following information):**
Chrome

**Additional context**
SSs taken on 10/05/2020. You can identify in both "Birds House" review. You can see entries counter. I deleted nominations' map, so you are able to see both nomination's history and search box.

**Comment by MrJPGames** [comment]
The date picker also has a time component. This time is set to the time of the last review by default. This was an unintended side-effect. For the time being you can change the end time to 23:59 and the start time to 00:00 to fix this issue.

Soon a new bug-fix release will come that disables the time range, solving this issue.
