### ISSUE TITLE
Support for UTM coordinate map arguments

### ISSUE THREAD

**Issue by sp00x** [MrJPGames/WayFarerPlus#179]
The current macros for map urls only support lat/lng coordinates, while various professional and national map services require UTM coordinates.

There exists several libraries for doing conversions, e.g. https://www.npmjs.com/package/utm

Would be good to have %easting% %northing% %zone% (and since most libraries offer this, %letter%) macros for use. 

Easting is often referred to as "x" and northing as "y", e.g. Norwegian map service of air photos have urls like: https://norgeibilder.no/?x=229499&y=6640196&level=16&utm=33. Here x= easting, y= northing, level= zoom, and utm= the zone number.

There's no good reasons not to add this, as it's quite common among professional map solutions.

**Comment by sp00x** [comment]
Actually, it was a bit more complicated than that, because some of these require the a specific UTM zone.

So, I just made a wrapper script `https://spoox.org/lat-lng-utm.html` - which takes arguments
`lat`, `lng`, `url` (URL escape this!), `zone` (optional) and allows you to replace parameters in the url, `%easting%`, `%northing%`, `%zoneNum%`, `%zoneLetter%`, and `%eastingFull%` and `%northingFull%` for float variants.

So e.g. the above would be `https://spoox.org/lat-lng-utm.html?lat=%lat%&lng=%lng%&url=https%3A//norgeibilder.no/%3Fx%3D%25easting%25%26y%3D%25northing%25%26level%3D16%26utm%3D%25zoneNum%25`

Another service, which requires UTM 33 (which the utm library doesn't always output) would be `https://spoox.org/lat-lng-utm.html?lat=%lat%1&lng=%lng%&zone=33&url=https%3A//norgeskart.no/%23%21%3Fproject%3Dseeiendom%26layers%3D1002%2C1014%26zoom%3D17%26lat%3D%25northingFull%25%26lon%3D%25eastingFull%25%26sok%3D%title%%26markerLat%3D%25northingFull%25%26markerLon%3D%25eastingFull%25%26panel%3DsearchOptionsPanel`

**Comment by MrJPGames** [comment]
I think this could be a nice addition. Since you closed the issue am I correct in thinking this is not a high priority issue?

For now I will reopen this issue if I decide to tackle it. However if you think this is of more importance (to others who might not know about your workaround) feel free to request a reopen, which will make sure I remember this issue when I dedicate time to WF+ development.

**Comment by sp00x** [comment]
Well I solved my own problems, and I closed it because I realized the complicating factor of some of these services requiring specific UTM zones as I am not sure how you would solve that by just having %macros%.

Maybe you could do support something like `%easting:33%` to force a certain UTM zone, and your substitution code would just do the conversions on the fly?
