### ISSUE TITLE
A select all/deselect all option on the nomination filter

### ISSUE THREAD

**Issue by mdooley98** [MrJPGames/WayFarerPlus#181]
By default I want all my nominations to show when I visit the /nominations page, so when I want to filter for one specific criteria I have to deselect all 7 others manually. An option to select/deselect all would be great

![image](https://user-images.githubusercontent.com/47961420/87467035-269c5000-c5cc-11ea-8b6e-325c7078bc62.png)

**Comment by MrJPGames** [comment]
That would definitly be useful! Thanks for the suggestion. As this should be a simple thing to add I'll see when I can get it out.
