### ISSUE TITLE
Select/deselect all on /nominations not working

### ISSUE THREAD

**Issue by mdooley98** [MrJPGames/WayFarerPlus#183]
The buttons do as they should and select/deselect all of the options, but the change doesn't go through when you click FILTER to confirm the changes. Manually selecting or deselecting individual options and then clicking FILTER still works

**Comment by MrJPGames** [comment]
This was fixed in commit da88ddf31eda79f3c493e74ac76e581917fd0a53

The update will take a little bit before it is reviewed by Chrome.
