### ISSUE TITLE
Plugin randomly not loading

### ISSUE THREAD

**Issue by cosmetify** [MrJPGames/WayFarerPlus#184]
**Describe the bug**
I've been reviewing with this plugin for a while now and randomly it just doesn't load. The dark theme stays activated, but all the other functions just don't work. I'm not sure what's causing it, but I started to notice somewhat of a trend. When there's a bunch of nearby POI (like 10+) is often times when it doesn't load. Perhaps it can't handle all of the nearby POI for some reason?

**To Reproduce**
Review until you find one that's in a heavily populated POI area

**Browser (please complete the following information):**
Firefox v79, Windows 10

**Additional context**
I'm not really seeing any errors in the console, but here's a [copy of the log](https://pastebin.com/raw/CQ84qPks) when it doesn't work (minus the insecure warnings). It seems to be happening more frequently now. Sometimes refreshing the page fixes it, but not every time.

**Comment by MrJPGames** [comment]
This issue should be fixed.
