### ISSUE TITLE
Session review counter

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarerPlus#190]
**Describe the feature you'd like**
In the header have the reviews done in the current session.

**Describe reasons NOT to add this feature**
Ugly, unneeded.

**Describe reasons to add this feature**
Useful to some, and having it off by default negates all negatives.

**Additional context**
Should be easy to do using session storage.

**Comment by Paranomix** [comment]
If history is on, you can easily see that. Right now, minus the edits, but they're supposed to be added, somewhere in the future.

**Comment by MrJPGames** [comment]
Added in update 2.0
