### ISSUE TITLE
Plugin broken after update to wayfarer

### ISSUE THREAD

**Issue by cosmetify** [MrJPGames/WayFarerPlus#192]
**Describe the bug**
Wayfarer updated today and changed some things. The home + submit button no longer shows, the submit button looks kinda weird, the star colors reverted back to orange, the timer is missing, the cells and other map edits no longer show among a few other things. The rating system is also different, check out your profile for that.

**To Reproduce**
Login and start reviewing

**Expected behavior**
Function properly

**Screenshots**
Here's a quick screen shot displaying a few of the issues listed above
![Untitled](https://user-images.githubusercontent.com/15617656/96637125-41c5dc80-12ec-11eb-8001-63a9ce12184f.png)

**Browser (please complete the following information):**
Tested both FF and Chrome

**Comment by MrJPGames** [comment]
Sorry for the late reply. This has (mostly) been fixed in 42de5260794d4a7de1bb2d450b37a4622dfe55a6

Firefox will receive this update in a few hours, to test the waters as far as stability/bugs. Then Chrome will also receive the update (which takes a bit due to the review process they have)

**Comment by crismorais** [comment]
Please don't forget the opera as well. Thaks
