### ISSUE TITLE
[BUG] Full zoom out for duplicate check

### ISSUE THREAD

**Issue by ultragreg** [MrJPGames/WayFarerPlus#199]
**Describe the bug**
The Maps for duplicate check is fully zoomed out since the last version of wayfarer+ (1.14.11.2)

**To Reproduce**
Go to a review Page

**Expected behavior**
Having the normal zoom

**Screenshots**
https://imgur.com/Lm0wGkQ

**Browser (please complete the following information):**
Chrome 86.0.4240.75 

**Additional context**

**Comment by MrJPGames** [comment]
To fix the issue for yourself, set the setting to something else and back.

I'll make sure the next update fixes the setting automatically.
