### ISSUE TITLE
[BUG] Hovering over "Open In" renders popup hundreds of pixels to the left

### ISSUE THREAD

**Issue by lollercopter** [MrJPGames/WayFarerPlus#202]
In Firefox 82.0.3 on OSX using Wayfarer+ 1.14.11.3, hovering over the "open in..." button renders the "Google Maps / Ingress Intel / OSM" popup several hundred pixels to the left. It is not possible to click any of these options because as soon as the mouse leaves the "open in..." button, the other popup disappears.

Here is a screenshot, which includes the steps to reproduce: https://i.imgur.com/yuzztvX.jpg

**Comment by MrJPGames** [comment]
Thanks for the report, the version that fixes this issue (1.14.12) will start rolling out shortly!
