### ISSUE TITLE
Translate buttons when asked in Edit modus for Best title, Best description or Best location

### ISSUE THREAD

**Issue by remcoderksen** [MrJPGames/WayFarerPlus#206]
Sometimes we get Edit screens instead of Review screens.
Here they ask for Best title, Best description or Best location when there are multiple options.
Translate buttons for the given titles and descriptions would be a good addition to Wayfarer+.
Usually they ask this because of typos people make but in other languages that I sometimes get I really have no clue what it says.

**Comment by MrJPGames** [comment]
This will be included in the 1.15 update that should be available later today for Firefox, and depending on review times sometime soon on Chrome!
