### ISSUE TITLE
Review Counter feature adding extra counts[BUG] 

### ISSUE THREAD

**Issue by ss7424** [MrJPGames/WayFarerPlus#213]
When reviewing, the counter starts off accurate but after hitting the 5th review, an additional count is entered. 

![PhotoGrid_Plus_1610552216460](https://user-images.githubusercontent.com/77402849/104479557-f3964180-5599-11eb-9d47-f3e530007f6c.jpg)

Additional information:
- Using the plug-in on Firefox for Android
- First occurred while reviewing normal submission, then secondly a location edit.

Firefox Version: 68.0 
Android version: 11
WF+ Version: 2.0

**Comment by MrJPGames** [comment]
Sorry I missed this issue.
However this bug should've been fixed in release 2.0.1 of WF+. As such I'll close this issue, if you are still experiencing this issue feel free to reopen it!
