### ISSUE TITLE
Clickable Links in additional Context field

### ISSUE THREAD

**Issue by MaxEtMoritz** [MrJPGames/WayFarerPlus#216]
**Describe the feature you'd like**
If a wayfinder has provided a weblink for additional info in the additional context field, it is not clickable in Wayfarer and you have to copy-paste it first. It would be awesome if WayFarer+ could scan the additional information for links and make them clickable without the need to copy-paste them.

**Describe reasons NOT to add this feature**
It is very rare that wayfinders provide links, so this could maybe be development time that is wasted for features that can be used more often.
You could accidentally click on the link and land on a site you wouldn't want to get to.

**Describe reasons to add this feature**
Seems easy and fast to do and would be a QoL improvement if a link is provided.

**Additional context**
I read a discussion on the wayfarer forum that stated that links in the additional context field are totally okay. Just not in the title or description.

**Comment by MrJPGames** [comment]
Great issue! Also amazing feature, I can't believe I haven't thought of this myself after all this time!

There is one complication, namely URLs come in many shapes and sizes, and not all can be supported. Meaning some not full URLs (missing http:// or https://) will not be detected, at least in the initial release.
