### ISSUE TITLE
Portal Criteria Changelog update notification (dot)

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarerPlus#50]
**Describe the feature you'd like**
This feature would create a "red dot" like in Wizards Unite to notify users of changes to the portal criteria. This is useful for many as it will allow them to easily stay on top of the most recent changes to the criteria!

**Describe reasons NOT to add this feature**
It would involve the occasional unauthorized web request to Wayfarer's servers. As it is only a simple HTML page with absolutely no technical or cheating relevance this should not be an issue, but should at least be considered in full before releasing this feature.

**Describe reasons to add this feature**
It will allow people to be better reviewers by knowing when the rules have changed/been clarified. This feature will make staying up-to-date more convenient as the user will not have to check (daily?) themselves just to see if there has been an update.

**Additional context**
This was thought of, and brought up by Liehon over on Reddit.

**Comment by MrJPGames** [comment]
Public URL: https://niantic.helpshift.com/a/wayfarer/?p=web&s=wayspot-acceptance-criteria&f=acceptance-criteria-update-log&l=en

This should enable the red dot without making web requests to any private pages!

**Comment by fortepc** [comment]
I absolutely love this idea! This is an excellent addition!

**Comment by MrJPGames** [comment]
Cancelled. With newer updates brining Criteria to Wayfarer itself, including future updates this feature would serve little to no purpose.
