### ISSUE TITLE
Presets should set WhatIsIt box

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarerPlus#75]

**Comment by fortepc** [comment]
oops! I didn't see this when I opened #77 sorry :sweat_smile:

**Comment by MrJPGames** [comment]
I was able to implement this. However any presets made before the 1.11.1 update will not have the WhatIsIt box set for them. This is because critical info was not being stored by older versions. However any presets made from 1.11.1 onward will work (unless Niantic changes things in an unfortunate way)
