### ISSUE TITLE
Save Review History and allow GeoJSON export

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarerPlus#80]
**Describe the feature you'd like**
There was an OPR userscrupt called opr-portal-tracker (https://www.reddit.com/r/Ingress/comments/9bds6k/opr_portal_tracker_userjs_to_track_locations/) . It would keep a geo log of what you reviewed, and how you reviewed it. I'd like that functionality to be added into this chrome extension

**Describe reasons NOT to add this feature**
There could be an argument made that Niantic wouldn't want us to do this. 

**Describe reasons to add this feature**
Being able to look back on the things you reviewed can be not only a cool bit of data, but it can be insightful to see whether a nomination you previously reviewed ultimately ended up getting accepted or not. Being able to look at your previous reviews, then viewing that nomination in the Ingress Intel map (to see if it ended up being accepted) would let you get a better idea of how you're voting on certain things compared to the majority of Wayfarer. 

**Additional context**
The export as GeoJSON was the coolest part, which you can see as a gist on my profile from when I was using this before. https://gist.github.com/fortepc/bdb8078c4cea3855261524564fcd0ae8

**Comment by fortepc** [comment]
I think it would be really cool to save every question in your history, but even if it only saved the basic information (Title, Description, Photo, Accept/Deny, Location) that would be awesome.

**Comment by MrJPGames** [comment]
I loved using that userscript back in the day. As such I have had this idea in the back of my head for quite some time too. 

The plan is/was to save everything there is to save. Title, description, photoURL, submission statement, addition photoURL and of course every rating including the WhatIsIt section.

This way users could see (for those that go live in Ingress) how they rated them. And would not really be cheating as theoretically you could write down every review you did.

**Comment by MrJPGames** [comment]
This has now been added (and is live on Firefox already!)
Though more expansion on this feature is still to come I will nevertheless close this issue as the core functionality has already been finished.
