### ISSUE TITLE
[BUG] Recon Offset only affects "Recon Medal" and "Progress to Gold" and does not affect the "Processed and Agreement"

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarerPlus#85]
**Describe the bug**
The profile tab still shows the original (innacurate) count for "Processed and Agreement" section when applying an offset

**To Reproduce**
1. Go to the extensions's settings
2. Add an offset (for me it was 1178)
3. Open https://wayfarer.nianticlabs.com/profile
4. See that the "Processed and Agreement" still shows the inaccurate number from the WayFarer reset.

**Expected behavior**
I expect if I set an offset to be able to see my actual agreements count. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26149601/71414237-f38c7200-2623-11ea-8445-497ab7659d4b.png)

**Browser (please complete the following information):**
Brave (Chrome Based)

**Additional context**
Maybe instead of totally overriding the "Processed and Agreement" stat like I initially expected, it would be better to show both, like this.
![image](https://user-images.githubusercontent.com/26149601/71414393-c2607180-2624-11ea-99b5-b1348e841d98.png)

Or maybe like this..
![image](https://user-images.githubusercontent.com/26149601/71414420-dc9a4f80-2624-11ea-8f12-e212694c44c7.png)

Yeah, I think I like that second one better. Adding the number into the Recon section.

**Comment by MrJPGames** [comment]
I think I will chose the second way of displaying it. Although I think it might be better to have it next to the progress instead of the current badge?

**Comment by fortepc** [comment]
Yeah, you're right. That would be the better place for it.

**Comment by kikifreena** [comment]
I'm not sure if this is related, but I think the "progress to gold" Recon badge feature is not displaying an accurate "progress to gold" percentage. The tiers begin with 100, 750, and then gold-2500 and platinum-5000 and onyx at 10k. However, I have 1266 agreements, and it's thinking I'm only around 25% of the way to gold.  It seems like the numbers aren't correct.

**Comment by MrJPGames** [comment]
> I'm not sure if this is related, but I think the "progress to gold" Recon badge feature is not displaying an accurate "progress to gold" percentage. The tiers begin with 100, 750, and then gold-2500 and platinum-5000 and onyx at 10k. However, I have 1266 agreements, and it's thinking I'm only around 25% of the way to gold. It seems like the numbers aren't correct.

25% seems a little off, are these agreements on the Ingress badge? Some agreements in Wayfarer do count towards upgrades and are shown by WayFarer+ as agreements when "Aproximation" setting is used for expanded profile.
Anyways if 1266 agreements is what you have on the Ingress badge the progress you should see is 29%, If this is what is being displayed this is correct: (1266-750)/(2500-750) ~= 0.29.
Though this might seem of if you were expecting an overall percentage and not a relative percentage compared to the previous already achieved tier. 
I am open to discussion on which is better, or a nice ways to allow users to choose between the two.

**Comment by MrJPGames** [comment]
The agreement display is now implemented. And will go live when the 1.11.1 update goes live (hopefully around a week from now, but no promises!)

The current implementation is to have the total displayed next to the progress percentage. Once Onyx is achieved this progress % will not disappear but will instead be replaced by the badge agreement stat.

**Comment by kikifreena** [comment]
> > I'm not sure if this is related, but I think the "progress to gold" Recon badge feature is not displaying an accurate "progress to gold" percentage. The tiers begin with 100, 750, and then gold-2500 and platinum-5000 and onyx at 10k. However, I have 1266 agreements, and it's thinking I'm only around 25% of the way to gold. It seems like the numbers aren't correct.
> 
> 25% seems a little off, are these agreements on the Ingress badge? Some agreements in Wayfarer do count towards upgrades and are shown by WayFarer+ as agreements when "Aproximation" setting is used for expanded profile.
> Anyways if 1266 agreements is what you have on the Ingress badge the progress you should see is 29%, If this is what is being displayed this is correct: (1266-750)/(2500-750) ~= 0.29.
> Though this might seem of if you were expecting an overall percentage and not a relative percentage compared to the previous already achieved tier.
> I am open to discussion on which is better, or a nice ways to allow users to choose between the two.

In Ingress and PoGo, the badges say 100 / 1000 etc. and the percentage bar in PoGo indicates the existing 100 of 1000 ("10 percent") when you reach a new "tier" even though leveling isn't done that way. I think this way would make more sense to what's already being done in the games. Likewise, Ingress does something similar - it doesn't display the number of agreements you have between silver to gold, etc. it displays the number of total agreements you've ever had. I'm having trouble converting between the two systems as of present implementation.
