### ISSUE TITLE
[BUG] Nomination unlocks incorrect date

### ISSUE THREAD

**Issue by Cotta-R** [MrJPGames/WayFarerPlus#88]
**Describe the bug**
Within the Nomination Stats at the Nomination page, there is written, when next nominations will unlock. The date of this is most probably wrong. It's one more day than written.

**To Reproduce**
1. Go to Nominations
2. Click on View Nomination Stats
3. Count with your fingers to 14
4. See error, output is one day to early

**Browser (please complete the following information):**
Windows 7, Firefox 71.0

**Comment by MrJPGames** [comment]
Sorry but based on this report I could not find any unexpected/wrong behavior in the Nomination estimates.

Could you please provide the following info:
- The dates of each of your nominations (within the last 20 days) (Just the date in enough)
- A screenshot of the Nomination Stats (just the prediction part is enough)
- What games you use to submit? Ingress, Pokemon Go, both?

**Comment by Cotta-R** [comment]
![grafik](https://user-images.githubusercontent.com/6556929/72226486-098db280-3592-11ea-8dbe-d2916738f22f.png)
![grafik](https://user-images.githubusercontent.com/6556929/72226584-ff1fe880-3592-11ea-8120-b0468c8aa423.png)

Game: Pokemon Go
Last submissions:
2 * 29.12.2019
2 * 30.12.2019
3 * 31.12.2019
sum: 7 submissions
and a new one from today, 12.01.2020.
Yesterday the prediction said, I would get 2 unlocks yesterday (11.1.), but in fact they unlocked just today.
Counting from 29.12., we have 30.12. and 31.12. in 2019 and 1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., and finally 12. in january 2020 to reach 14.
Other example, my latest submission is from today, 12.01.2020, and it says, this one will unlock an new submission on 25.01.2020. But the time span of 14 days will end on 25.01.2020.
In fact, new submissions obviously will unlock in 14*24h, as they were not available in morning but in evening.

**Comment by MrJPGames** [comment]
Thanks for your thorough report! It should be fixed later today. Hopefully the update with the fix will be live on Firefox later today as well, Chrome will have to finish their review process which can take between hours and days, so no ETA on that one sadly.
