### ISSUE TITLE
[BUG] NaN at # of unlocks

### ISSUE THREAD

**Issue by Cotta-R** [MrJPGames/WayFarerPlus#97]
**Describe the bug**
Within the "VIEW NOMINATION STATS", there is a NaN (not a number) at # of unlocks, see attached Screenshot.

**To Reproduce**
Happened the first time for me, but persistent after a restart of browser.
Maybe, if related, I just nominated new objects today.
Further, but maybe unrelated, I nominated 4 objects today, got for all of them confirmation mails, but so far only 3 appeared on my wayfarer page.

**Browser, Game and OS
Windows 7, Firefox 72.0.1 and Pokemon Go

**Screenshots**

![nominationscreen01](https://user-images.githubusercontent.com/6556929/72760653-d07cc000-3bd9-11ea-8ae7-61d9afaeacbd.png)

![nominationscreen02](https://user-images.githubusercontent.com/6556929/72760672-dc688200-3bd9-11ea-99d0-a5cba0256831.png)

**Comment by Cotta-R** [comment]
A day later, # of unlocks works as expected.

**Comment by MrJPGames** [comment]
Thanks for the report, and great info! I will definitely investigate the original issue and try to fix it.
