### ISSUE TITLE
[BUG] Countdown timer is off

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarerPlus#99]
**Describe the bug**
I want to have a submit countdown of 20 seconds. When I enter 20 seconds, it starts at 21. To have it at 20 I need to set 18 for whatever reason.

**To Reproduce**
Not provided (Probably just start a review)

**Expected behavior**
Countdown to start where I set it, which it did a couple days ago.

**Browser (please complete the following information):**
Latest Chrome (version ???) on Win7

**Additional context**
Originally reported by @SfSuicune

**Comment by MrJPGames** [comment]
Was unable to reproduce. Could you (@SfSuicune) possibly provide screenshots and additional information regarding this issue?

**Comment by SfSuicune** [comment]
Right now the submit countdown is just off by 1 second for some reason and not 2 anymore.

As you can see here, I set 20 and it starts at 21:
![21](https://user-images.githubusercontent.com/24555476/72902631-1e094200-3d2c-11ea-83e5-2addb4e822c2.png)

That's basically everything I can tell you.
Not a major issue, I just noticed it.

**Comment by MrJPGames** [comment]
So after some investigation the root cause is that both timers are updates once every second. However not necessarily at the same time. Both use rounding too. What this can cause is a moment in time where the two timers seem to be desynced by at most 2 seconds. Both are in fact at most 1 second off the true time, but if they are both off just right the perceived distance can be bigger. I have implemented a slight modification that at least should make this happen less often due to nicer rounding.
As this is not a true "fix" I'll simply close the issue now. However something akin to a fix is coming later today together with some other small bug fixes.
